### PR TITLE
words have meaning: renames master branch to main and updates references to master

### PR DESCRIPTION
**Pull request by srhrshr**
@desilinguist , 

This is in reference to #625 - thanks for raising a very thoughtful issue!

I've followed the [link you shared above](https://medium.com/faun/git-step-by-step-renaming-a-master-branch-to-main-16390ca7577b) and have completed steps 1-4 along with step 9 of updating references to `master` in the code.

Steps 5-8 and 10 on the same link needs to be done on your end (or whoever has the admin privileges to the repo). 

Let me know if there are any other changes you envisioned as part of the `master` > `main` change.

Thanks!

### CODE REVIEW

**Comment by desilinguist** [comment]
Thanks so much for submitting this PR @srhrshr! I will take a look over the next few days and try to get the other steps finished as well.

**Comment by desilinguist** [comment]
Actually, I think what will be easier is if I create a `main` branch and then you can modify your PR target to the that `main` branch so that `master` is completely unaffected and nothing breaks until we change the default branch.

**Comment by desilinguist** [comment]
Okay,  the `main` branch has been created. Can you please change the target for your PR to be `main` instead of `master` @srhrshr ?

**Comment by srhrshr** [comment]
Done @desilinguist.

**Review by desilinguist — APPROVED** [review]
LGTM 👍

**Pull request merged**
