### PR TITLE
[WIP] raise warning f1_score_micro equals accuracy

### PR DESCRIPTION
**Pull request by ananyaganesh**
Raises warning that micro-averaged F1 score is the same as accuracy for multi-class classification.
Addresses #491

### CODE REVIEW

**Comment by mulhod** [comment]
Should this still be WIP?

**Comment by desilinguist** [comment]
Yes, this is still WIP since it's likely to change based on how we resolve #502

**Comment by bndgyawali** [comment]
I did not realize it is WIP. I saw that the build passed, and approved. I do not find how to unapprove it.

**Comment by bndgyawali** [comment]
The coverage is down though.

**Pull request closed without merging**
