### PR TITLE
Fix a bug in print_model_weights for multi class classification

### PR DESCRIPTION
**Pull request by aoifecahill**
Also added a test for this case.

### CODE REVIEW

**Comment by desilinguist** [comment]
Looks like this PR fails on the gridmap-enabled builds because `drmaa` throws the following error:

```python
InternalException: code 1: reresolve hostname failed: hostname exeeds hostname length(MAXHOSTNAMELEN) on this system
```

@dan-blanchard, any ideas?

**Comment by dan-blanchard** [comment]
It's a bug with Travis.  We could [add this workaround](https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165131913) to our `.travis.yml`, or just wait for them to fix it (since it looks like they've been working on it in the last 24 hours).  Relevant issues: travis-ci/travis-ci#5292 and travis-ci/travis-ci#5227.

**Comment by desilinguist** [comment]
I think we can wait another day or two.

**Comment by desilinguist** [comment]
I think we might need to apply the workaround now. It's been too long and they haven't fixed it.

**Pull request merged**
