### PR TITLE
Do not return 0 if metric value is nan in correlation function

### PR DESCRIPTION
**Pull request by mulhod**
Addresses #585.

### CODE REVIEW

**Comment by mulhod** [comment]
This will have to wait until #586 is finished.

**Comment by mulhod** [comment]
This is ready for review now.

**Comment by mulhod** [comment]
Does someone else have time to review this? @aoifecahill @bndgyawali @ananyaganesh @AVajpayeeJr @chaomenghsuan

**Comment by desilinguist** [comment]
@mulhod I merged `master` into this just to double check that nothing breaks with the new scikit-learn.

**Comment by mulhod** [comment]
Even though it says this passed all checks, there was one failure that still needs to be investigated. I'm not sure why it says all checks passed.

**Comment by mulhod** [comment]
This is good to go now.

**Pull request merged**
