### PR TITLE
Bugfix/update config.py

### PR DESCRIPTION
**Pull request by mulhod**
Fix minor errors that I noticed while going through config.py.

### CODE REVIEW

**Comment by mulhod** [comment]
I don't really know why this is failing. The errors don't seem to be in any way related to the PR, which would be very unexpected anyway. But other recent PRs haven't failed in a similar way, so I don't really know.

**Comment by dan-blanchard** [comment]
Binstar went down yesterday for a bit, so that's why it was failing. I restarted it.

**Comment by mulhod** [comment]
Any chance we can try to do the build again for this one again? Is there any reason to think that it's failing due to what's in the PR?

**Comment by dan-blanchard** [comment]
The issue was that they changed the default path for where miniconda gets installed, which broke all our travis builds.  I fixed that in master and then rebased your branch, so everything went fine after that.

**Comment by mulhod** [comment]
Thanks.

**Pull request merged**
